### ISSUE TITLE
Ruin Description text area

### ISSUE THREAD

**Issue by SpaceDiceMan** [Stefouch/myz-zonemap#1]
Ruin description text area is too small. As such you cant read what's written there. When it's rolled for first time it's large enough, but when rerolling or changing the txt it remains too small.
Same for Mood.

**Comment by Stefouch** [comment]
Actually, it's a bug related to the framework I used and I need to figure a turn around. Meanwhile, the text area's size adjusts itself as soon as you type something inside.

**Comment by Stefouch** [comment]
This bug should be fixed now.
