### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by AbraKadabraham** [Stefouch/myz-zonemap#26]
Hi,

i have created a german translation based on the german core rulebook, file is attached. Let me know if this is ok for you, or if i should send it to you per mail or something.

Best Regards
AbraKadabraham

[sector-generator-de.json.txt](https://github.com/Stefouch/myz-zonemap/files/5164622/sector-generator-de.json.txt)

**Comment by Stefouch** [comment]
Hi @AbraKadabraham !

Thank you very much for your contribution.

I'll soon update the app with the new language.
