### ISSUE TITLE
Like/Donation Button

### ISSUE THREAD

**Issue by SpaceDiceMan** [Stefouch/myz-zonemap#8]
There is nowhere where you can show appreciation for this really great tool!!!!
[which I love, and all I can do is create ''issues'']

**Comment by Stefouch** [comment]
Since I'm using licensed work, I'm not very sure I can show a donation button.

**Comment by Stefouch** [comment]
What is advised to use? Paypal.me? Patreon? Tipeee?

**Comment by SpaceDiceMan** [comment]
Not an expert, but I often see this:
https://www.buymeacoffee.com/
