### ISSUE TITLE
Easy map creation

### ISSUE THREAD

**Issue by SpaceDiceMan** [Stefouch/myz-zonemap#9]
People that have a background map will want the Enviroments to match the map (most of the time). As these maps are often based on ruined cities and their surroundings there are two main types of enviroment Ruins or Nature (In the rules the difference whether a ruin is present or not (table result 11-32 and 33-66). Perhaps allow a single button to swap between these two options, so that they can easily match their sectors to their background (instead of keeping rerolling untill they either get Nature or Ruins).
[You might add Industry and Settlement as seperate option as well, but that kills the quick single button. Once again if you want to match terrain for 30x18 sectors, ease is important]

**Comment by Stefouch** [comment]
Unfortunately, this not something I plan to implement. I'm not really convinced by this idea since spamming the "roll" button a few times will have the same result.

**Comment by SpaceDiceMan** [comment]
Good point, didnt think of that.
